wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [42]
    rows: [9, 17, 5]
  refreshInterval: 1
  mods:
    prettyweather:
      enabled: true
      city: "champaign"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      unit: "u"
      view: 0
      language: "en"
    gcal:
      email: "soehlert@es.net"
      enabled: true
      eventCount: 5
      hourFormat: "12"
      multiCalendar: false
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      secretFile: "~/.config/wtf/client.json"
      showDeclined: false
      timezone: "America/Chicago"
      withLocation: true
    todoist:
      apiKey: "7cb12c1ea9aeb6483624a6ade291206c18c68a29"
      enabled: true
      position:
        top: 2
        left: 0
        height: 5
        width: 1
      projects:
        - 2233114868
        - 2233114780
      refreshInterval: 3600
